Date update
bcc2020/bcc2020.github.io pull request #27
Opened 2020-03-23 17:47 UTC by denis-yuen

n/t

2020-03-23 17:52 UTC, nlharris requested changes
Thanks, looks good except for the correction I noted on the submit page.

2020-03-23 17:52 UTC, nlharris commented on _includes/submit.md
> +Abstract submissions will open on April 30, 2020.
Abstract submission will CLOSE on April 30, 2020.

2020-03-24 20:31 UTC, tnabtaf approved these changes

2020-03-30 18:47 UTC, morgantaschuk approved these changes

2020-03-30 19:58 UTC, nlharris approved these changes
looks good, thanks. check with @tnabtaf whether we should change the date it says registration will open, if it doesn't seem like we'll be able to open it tomorrow.

2020-03-30 22:02 UTC, nlharris commented
"Registration opens" needs to be changed to "Early April".

2020-03-31 19:27 UTC, closed without merging

2020-03-31 19:27 UTC, denis-yuen commented
(seems superseded by other PR)

2020-03-31 19:28 UTC, nlharris commented
sorry, denis--i hadn't seen that you made that change!

2020-03-31 19:52 UTC, denis-yuen commented
No worries!