added dates for cofest
bcc2020/bcc2020.github.io pull request #33
Opened 2020-04-19 06:25 UTC by nlharris

ya gotta say the dates, not just the days of the week...

2020-04-21 20:07 UTC, morgantaschuk commented
I made a conflict and fixed it.

2020-04-21 20:07 UTC, morgantaschuk approved these changes

2020-04-22 00:30 UTC, heuermh approved these changes
Thank you, @nlharris @morgantaschuk!

2020-05-11 16:35 UTC, heuermh requested changes
Sorry, didn't notice before (I am very bad at calendars) but the dates here aren't correct and also don't match the days of the week.  Shouldn't it be

Tuesday and Wednesday, July 21 - 22
Thursday and Friday, July 23 - 24

2020-07-08 18:54 UTC, closed without merging