Going Global and Registration Open
bcc2020/bcc2020.github.io pull request #34
Opened 2020-04-20 23:29 UTC by tnabtaf

Site wide update, publishing that we are open for registration, and that we are going global.  Also links to schedule web site.

2020-04-20 23:46 UTC, heuermh requested changes
Minor typos

2020-04-20 23:46 UTC, heuermh commented on _config.yml
> +ticketsInfo: "There are separate registrations for training, the confernce, and the CoFest events."
confernce &rarr; conference

2020-04-20 23:46 UTC, heuermh commented on _includes/schedule.html
> +        <p style="text-align: left;">The <a href="../cofest/">CollaborationFest</a> will follow the meeting, and span the entire world (nothing new there).  There will be core communities during both
continuosly &rarr; continuously

2020-04-20 23:46 UTC, heuermh commented on _includes/training.html
> +            <p style="text-align: left;">Training is offered over two days: July 17-18 in the <a href='https://bcc2020.sched.com/venue/West'>West</a>, and July 18-19 in the <a href='https://bcc2020.s
regiester &rarr; register

2020-04-20 23:46 UTC, heuermh commented on _posts/2020-04-20-registration-open.markdown
> +2. Be aware that the East training schedule is not yet finalized.  If you are in the east, you shouldhold off until the end of April to register.
shouldhold &rarr; should hold

2020-04-21 00:17 UTC, tnabtaf commented on _posts/2020-04-20-registration-open.markdown
> +2. Be aware that the East training schedule is not yet finalized.  If you are in the east, you shouldhold off until the end of April to register.
Thanks.  Fixed, I think.

2020-04-21 00:17 UTC, heuermh approved these changes

2020-04-21 21:26 UTC, merged

2020-04-22 00:31 UTC, heuermh commented
Thank you, @tnabtaf @denis-yuen @morgantaschuk!