Improve navigation; highlight keynotes
bcc2020/bcc2020.github.io pull request #44
Opened 2020-05-25 20:53 UTC by morgantaschuk

- Fixed the 'Partners' page so that sponsors are first and other partners are second; fixed the dead link on that page
- Moved the 'Promote' nav bar item under the 'About' section
- Prominently add Keynote speakers to the front page and schedule page, and add their bios
- Moved the 'Training' nav bar item to the 'Schedule section'
- Changed the text on the Submissions page to state that abstract submissions are closed
- Other tweaks and fixups

2020-05-25 21:26 UTC, heuermh requested changes
LGTM, thank you, @morgantaschuk!  Found one typo, see review comment

2020-05-25 21:26 UTC, heuermh commented on _posts/2020-02-11-training-vote.markdown
> +**Vote for the Training Topics you want!)**
Missed removing `)` here

2020-05-26 14:16 UTC, morgantaschuk commented on _posts/2020-02-11-training-vote.markdown
> +**Vote for the Training Topics you want!)**
Thanks! Fixed.

2020-05-26 14:34 UTC, denis-yuen commented on README.md
> +Template is brought by [GDG Lviv](http://lviv.gdg.org.ua/) team. Substantial modifications were made to get it working for a non-GDG event.
Link doesn't work or is down

2020-05-26 14:34 UTC, denis-yuen approved these changes

2020-05-26 14:44 UTC, morgantaschuk commented on README.md
> +Template is brought by [GDG Lviv](http://lviv.gdg.org.ua/) team. Substantial modifications were made to get it working for a non-GDG event.
Fixed

2020-05-26 23:49 UTC, tnabtaf approved these changes

2020-05-27 15:31 UTC, merged